server:
    port: 8000
spring:
    cloud:
        gateway:
            routes:
                - id: product-service
                  uri: http://localhost:8081
                  predicates:
                      - Path=/products/**
                - id: order-service
                  uri: http://localhost:8082
                  predicates:
                      - Path=/orders/**
            globalcors:
                corsConfigurations:
                    "[/**]":
                        allowedOrigins: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
